chore: add Russia and Ukraine to list of OFAC blocked countries
WalletConnect/blockchain-api pull request #336
Opened 2023-10-31 09:04 UTC by xav

# Description

Update the list of OFAC blocked countries to include Russia and Ukraine

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-10-31 09:09 UTC, xDarksome approved these changes

2023-10-31 09:10 UTC, merged

2023-10-31 09:10 UTC, geekbrother requested changes
OFAC has blocked Ukrainian regions, not the country. These regions in 90% of cases use Russian IP blocks, because use Russian internet operators. As I know the situation from the inside, there is almost no chance that someone can use Ukrainian IP from the Donetsk and Crimea regions. In this case, we are blocking the whole country.

2023-10-31 09:12 UTC, xav commented
> OFAC has blocked Ukrainian regions, not the country. These regions in 90% of cases use Russian IP blocks, because use Russian internet operators. As I know the situation from the inside, there is almost no chance that someone can use Ukrainian IP from the Donetsk and Crimea regions. In this case, we are blocking the whole country.

Our lawyer told us we need to block Ukraine. Unfortunately, I have no information on a region block and anyway, we can't do that with the current blocker :(

2023-10-31 14:50 UTC, Hirama commented
You can confidently revert to Web2, as the notion of Web3 may be unrealistic for you.

2023-10-31 15:10 UTC, 0xBillyLoomis commented
Time for a hostile fork it seems since y'all can no longer uphold the values of web3

2023-10-31 15:36 UTC, GarageInc commented
you should have resisted this, not joined in!

2023-10-31 16:01 UTC, pugson commented
what the fuck

2023-10-31 16:18 UTC, maltsevoff commented
it's not cool at all, guys 
 
Ukraine is in the top by crypto adoption in the world. Also me as Ukrainian developer contributed into your repositories to make them better

and here we come...

2023-10-31 17:01 UTC, AyiSoli commented
Bitcoiners proved right, once again. 

Ethereum wallets blocking off entire countries. 

Every single project built on Eth/web3 nonsense only furthers the fact that all this B.S. is centralized tech built by people placed diametrically opposite to any cypherpunk ethos.

Needless to say, all this ETH/Web3 is grossly overvalued floatsam that will sink to the bottom of the ocean, where it rightfully belongs. 

Honest builder still developing on these centralized tech platforms still have time to put their delusions aside and contribute to actual decentralized tech stacks.

2023-10-31 18:00 UTC, ramka808 commented
Да вы афигели🤬

2023-10-31 18:07 UTC, kumancev commented
Yes! This is how we celebrated 15 years of bitcoin whitepaper 🎂

2023-10-31 18:12 UTC, jedcli commented
похуй

2023-10-31 18:15 UTC, yangwao commented
Seems Ukraine was removed

https://github.com/WalletConnect/blockchain-api/pull/338

2023-10-31 18:15 UTC, h0tw4t3r commented
Chill, it's back https://github.com/WalletConnect/blockchain-api/pull/338

2023-10-31 18:17 UTC, szupion commented
позор

2023-10-31 18:32 UTC, iower commented
WEB3 IS NOT A PLACE FOR DISCRIMINATION :see_no_evil: 

Or WalletConnect is not web3?

2023-10-31 18:37 UTC, myraincoat commented
shame on you!

2023-10-31 19:09 UTC, Specyonax commented
Decentralization Builders - lol

2023-10-31 19:17 UTC, 1ort commented
Is that what you mean when you talk about decentralization and web3? Absurd and shameful

2023-10-31 19:29 UTC, usrbad commented
That's as shame as ridiculous.

2023-10-31 19:35 UTC, LeslieOA commented
What's the longer term solution to this?
I can entirely understand that it doesn't make Good Business Sense™️ to ignore your lawyers, but am also disappointed in the move (Russian citizens aren't their government). 
Does something like WalletConnect need to be reimagined as a protocol more akin to Bittorrent or Holepunch help?

2023-10-31 20:15 UTC, moondayli commented
> > OFAC has blocked Ukrainian regions, not the country. These regions in 90% of cases use Russian IP blocks, because use Russian internet operators. As I know the situation from the inside, there is almost no chance that someone can use Ukrainian IP from the Donetsk and Crimea regions. In this case, we are blocking the whole country.
> 
> Our lawyer told us we need to block Ukraine. Unfortunately, I have no information on a region block and anyway, we can't do that with the current blocker :(

Hire a new fucking lawyer, this is just stupid on so many levels

2023-10-31 21:27 UTC, gosuto-inzasheru commented
you need a new lawyer AND THE GUTS TO TALK BACK TO HIM

2023-10-31 23:06 UTC, melonges commented
Вставай Донбасс!

2023-10-31 23:30 UTC, Corfucinas commented
Seriously consider firing your legal team

2023-11-01 00:16 UTC, pcfreak30 commented
Can't say I didn't see this coming. Web3 is a meme and we need to start fixing it. Assuming all of walletconnect is open, a community fork can be made thats not VC funded and can use P2P tech if required (I actually use holepunch @LeslieOA) .

See https://docs.lumeweb.com/better-web :upside_down_face:, my project is fixing this and yes I am shilling my FOSS project here, as it is warranted :P.

2023-11-01 06:44 UTC, nebolax commented
WTF dudes this is not how you should play in web3.

2023-11-01 07:52 UTC, amakuramio commented
Most hackers are from Russia, last two times my wallet was exploited were by Russian hackers (first one was crystalgame.io with Russian text in site source, and second one was Russian based DEX > Russian named adds) but they just use VPN so this would be useless. Useless commit lol

2023-11-01 08:00 UTC, nebolax commented
> Most hackers are from Russia, last two times my wallet was exploited were by Russian hackers (first one was Russian woman who later turned out to be a man texted me crystalgame.io with Russian text in site source, later threatened me, and second one was Russian based DEX > Russian named adds and Russian whatsapp me) **but they just use VPN** so this would be **useless**, right?

But then you should use some scanner and scam-detector and check the websites you visit. Logic "In this country there are more hackers than in other countries, so let's make it more difficult for **everybody** in this country to use web3" won't get us in any good situation.

2023-11-01 08:12 UTC, amakuramio commented
> > Most hackers are from Russia, last two times my wallet was exploited were by Russian hackers (first one was Russian woman who later turned out to be a man texted me crystalgame.io with Russian text in site source, later threatened me, and second one was Russian based DEX > Russian named adds and Russian whatsapp me) **but they just use VPN** so this would be **useless**, right?
> 
> But then you should use some scanner and scam-detector and check the websites you visit. Logic "In this country there are more hackers than in other countries, so let's make it more difficult for **everybody** in this country to use web3" won't get us in any good situation.

They're 200 IQ geniuses🤣 this commit won't stop them in any way, but will be an annoyance for small people who can't afford a good vpn, again the innocent suffering the most

2023-11-01 08:28 UTC, matthiasgeihs commented
Just let apps decide what countries to block? It's them who need to be compliant, right?

2023-11-01 09:28 UTC, TheFuzzStone commented
> Our lawyer told us we need to block ... 

Isn't that beautiful? DeFi/web3-4-5 is showing its true nature.

2023-11-01 16:34 UTC, bumblefudge commented
> Just let apps decide what countries to block? It's them who need to be compliant, right?

if only it were that simple... 

may i recommend some light reading to get up to speed with the basics of the topic:
https://www.amazon.com/Underground-Empire-America-Weaponized-Economy/dp/0241624517

2023-11-02 08:28 UTC, TheFuzzStone commented
The funny thing - people made a fuss when they added Ukraine and Russia. 

Yeah, don't give a shit about people in Iran, Cuba, North Korea and Syria. Fuck them. 

They already live in dictatorial regimes, they're used to it, so it's okay to make life even harder for them.

2023-11-02 08:50 UTC, moondayli commented
Seriously speaking this will lead to you guys losing most of your customers and people will start looking into alternatives

2023-11-02 09:47 UTC, matthiasgeihs commented
> > Just let apps decide what countries to block? It's them who need to be compliant, right?
> 
> if only it were that simple...
> 
> may i recommend some light reading to get up to speed with the basics of the topic: https://www.amazon.com/Underground-Empire-America-Weaponized-Economy/dp/0241624517

you may, but you may also give us the gist here?

2023-11-02 17:01 UTC, mmeitneriumm commented
![image](https://github.com/WalletConnect/blockchain-api/assets/61113097/63c0a167-81f7-4d5c-ae7a-4d81d3a8352d)

2023-11-03 11:29 UTC, Overtorment commented
this Fi is not very De

2023-11-04 08:10 UTC, DragonFrai commented
It's time to make a fork for those who live in a free country. For example.. Russia?

2023-11-07 09:36 UTC, blockedby commented
UPD:
![image](https://github.com/WalletConnect/blockchain-api/assets/66838646/da392217-fca7-42e4-a92a-f7406c261f1e)