chore: adding the span with request-id for handlers
WalletConnect/blockchain-api pull request #387
Opened 2023-11-22 18:58 UTC by geekbrother

# Description

The following changes are made:
* Adding the tracing span with the `request-id` for each of the handlers,
* The request-id can be provided in the headers as the `x-request-id` or generated as the UUIDv4 if not provided,
* Adding additional tracing `instrument` to the functions and logging.

Resolves #372

## How Has This Been Tested?

Not tested, but the approach was tested in isolation.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-11-22 22:15 UTC, arein approved these changes
looks functional but does `axum` not allow some sort of middleware to do this without code duplication?

2023-11-22 22:16 UTC, arein requested changes

2023-11-22 22:16 UTC, arein commented on src/providers/mod.rs
> +                info!("Selected provider: {}", provider);
we have 400mio RPC calls per month?  this would be 400mio requests. Can you only add the provider to the span such that if we see an error we see which provider it was for but not actually log it?

2023-11-23 00:13 UTC, geekbrother commented on src/providers/mod.rs
> +                info!("Selected provider: {}", provider);
Totally makes sense! Thanks for pointing out this. I've removed this noisy info and put the provider into the span field only.

2023-11-23 01:06 UTC, chris13524 requested changes
@arein How will this request ID be used? You won't be able to see this from an error. If you provide the requestId header then you could determine which provider is in-use. Just not sure this was fully through through.

2023-11-23 10:44 UTC, geekbrother commented
Can be done in a more elegant way, back into the draft.

2023-11-23 22:37 UTC, geekbrother commented on src/handlers/identity.rs
> +    let _enter = span.enter();
I've updated the implementation and this issue is solved.

2023-11-23 22:38 UTC, geekbrother commented on src/handlers/mod.rs
> +            .unwrap_or("invalid header value in `x-request-id`")
I've updated the implementation and this issue is solved.

2023-11-23 22:42 UTC, geekbrother commented
> @arein How will this request ID be used? You won't be able to see this from an error. If you provide the requestId header then you could determine which provider is in-use, but the real world doesn't set request IDs. Just not sure this was fully through through.

The implementation is updated and now the `x-request-id` is exposed to the **response's** headers and it's generated if not provided, so it can be tracked after the request is made. 
Please take a look at the new description. Now it's more usable.

2023-11-23 22:52 UTC, geekbrother commented
> looks functional but does `axum` not allow some sort of middleware to do this without code duplication?

I started to "reinvent bicycle" and found that we can just use tower [request_id middleware](https://docs.rs/tower-http/latest/tower_http/request_id/index.html) 🤦🏻 So I threw away my "re-invented wheel" and just replaced with this elegant and functional way.

Now the `x-request-id` header can be passed in the request, generated as UUIDv4 if not provided, and exposed to the response as a header to trace it after the request.

Additional tracing `instrument`s spans for handlers and providers was extracted into the #391 for a better review experience.

2023-11-24 05:53 UTC, arein commented
@chris13524 Max set a default request id.

For now when we have issues and use curl or a browser to see what's up we will be able to grab the request id to quickly confirm which provider failed.

Later we could possibly generate the request id in our SDKs and pass it along.

Also during error discovery in the logs this can be helpful to pull together more data for a single request.

IMO this would've certainly helped for some of the issues this week.

2023-11-24 05:54 UTC, arein approved these changes
Nice!

2023-11-24 16:09 UTC, chris13524 requested changes
This doesn't generate an `x-request-id` header if one doesn't already exist. You need [`SetRequestId`](https://docs.rs/tower-http/latest/tower_http/request_id/struct.SetRequestId.html) for that

2023-11-24 16:10 UTC, chris13524 approved these changes
Ah nevermind I see `.set_x_request_id(MakeRequestUuid)` now

2023-11-24 16:11 UTC, geekbrother commented
> This doesn't generate an `x-request-id` header if one doesn't already exist. You need [`SetRequestId`](https://docs.rs/tower-http/latest/tower_http/request_id/struct.SetRequestId.html) for that

Plz check the *Testing manually* in the description to test it locally ;)

2023-11-27 09:07 UTC, merged