feat(onramp): Coinbase transaction status
WalletConnect/blockchain-api pull request #388
Opened 2023-11-22 23:41 UTC by arein

# Description

Integrates Coinbase's transaction history behind feature flag. Allows us to show a prettier UI if a user onramped via Coinbase. Ultimately this should work for all on-/off-ramp providers and deserves some thought. But no harm in adding this behind a feature flag IMO.

## How Has This Been Tested?

Integration tests.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-11-24 15:56 UTC, chris13524 requested changes

2023-11-24 15:56 UTC, chris13524 commented on src/providers/coinbase.rs
> +            &address
security: doesn't look like this is exploitable yet, but we should URL encode `address` so they can't inject a `/` and do anything nasty (e.g. if Coinbase adds a new endpoint)

Looks like same issue with Zerion endpoint which would be good to fix too.

2023-11-27 17:59 UTC, geekbrother commented on src/providers/coinbase.rs
> +            &address
I think we can use `H160` type for the address argument and parse it somewhere at the upper level to prevent injecting, [like in the identity handler](https://github.com/WalletConnect/blockchain-api/blob/80228a549cad67724f8e96c97806c4783200dc3c/src/handlers/identity.rs#L65).

2023-12-06 12:30 UTC, geekbrother commented
I'll take over this as I'm on the blockchain-api work for the on-ramp transactions history.

2023-12-21 10:42 UTC, geekbrother commented on src/providers/coinbase.rs
> +            &address
Fixed. I've changed to use `H160` as a type for the address in [0c3bc](https://github.com/WalletConnect/blockchain-api/pull/388/commits/0c3bc1389920e492939407076c04a243b7dbf116).

2023-12-21 12:49 UTC, chris13524 requested changes
Only thing blocking is the `error` -> `info` log change. Otherwise a bunch of nitpicks but logic seems correct.

2023-12-21 12:49 UTC, chris13524 commented on src/handlers/history.rs
> +    if let Some(_onramp) = query.onramp.clone() {
I would prefer checking this more explicitly:

```suggestion
    if query.onramp.as_ref() == Some("coinbase") {
```

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        );
Pretty sure this could be simplified?

```suggestion
        let base = format!("https://pay.coinbase.com/api/v1/buy/user/{address}/transactions");
```

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        );
Pretty sure this could be simplified?

```suggestion
        let base = format!("https://pay.coinbase.com/api/v1/buy/user/{address}/transactions");
```

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        url.query_pairs_mut().append_pair("page_size", "50");
Nice using functions to build the URL!

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        error!(
Replace with `info!()`?

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        };
`.map_err()` and `.tap_err()` and turbofish is nicer IMO

```suggestion
        let body = serde_json::from_slice::<CoinbaseResponseBody>(&bytes)
            .tap_err(|e| error!("Error on parsing coinbase transactions response: {e:?}"))
            .map_err(|_| RpcError::TransactionProviderError)?;
```

2023-12-21 12:49 UTC, chris13524 commented on src/providers/coinbase.rs
> +        }
`reqwest` crate makes all a lot easier with the [`.json()`](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json) helper.

2023-12-21 12:51 UTC, chris13524 commented on integration/integration.test.ts
> +    it('fulfilled history with coinbase', async () => {
Technically this test doesn't actually test txns received from Coinbase, so we should add that if we can in the future.

2023-12-21 13:49 UTC, geekbrother commented on src/providers/coinbase.rs
> +        error!(
Thanks for catching this! I've missed this from the original PR, it seems it was added for debugging purposes.
I've removed it as well as other `info!` and added the `instrument` in the [f7c3ea](https://github.com/WalletConnect/blockchain-api/pull/388/commits/f7c3ea4c3a88d7c47609c65b12dcaa28c73d8558).

2023-12-21 16:58 UTC, chris13524 approved these changes

2023-12-22 01:12 UTC, chris13524 reviewed
The branching changed, so that may be wrong now. Are you sure that's right?

Also not blocking but not sure why you complicated the H160 string conversion with `{:#x}` now because `.to_string()` and `{}` already format it as hex as we would need.

2023-12-22 01:12 UTC, chris13524 commented on src/handlers/history.rs
> +    } else {
Is this branching correct? Don't we still want to do the normal history provider when Coinbase is enabled?

2023-12-22 01:12 UTC, chris13524 commented on src/providers/coinbase.rs
> +            &address
Does this not work? You were using `.to_string()` before and that's what `{}` formatting calls.

```
            "https://pay.coinbase.com/api/v1/buy/user/{address}/transactions",
```

https://docs.rs/fixed-hash/0.8.0/src/fixed_hash/hash.rs.html#219

2023-12-22 01:12 UTC, chris13524 commented on src/providers/coinbase.rs
> +                    sent_to: format!("{:#x}", address),
Lol I think this was already better:

```suggestion
                    sent_to: address.to_string(),
```

2023-12-22 01:17 UTC, geekbrother commented on src/providers/coinbase.rs
> +                    sent_to: format!("{:#x}", address),
`address.to_string()` when the address is `H160` returns a short address instead of the full version.

2023-12-22 01:19 UTC, geekbrother commented on src/providers/coinbase.rs
> +            &address
`address.to_string()` when the address is H160 returns a short address instead of the full version here. That's why `{:#x}` was used.

2023-12-22 01:21 UTC, geekbrother commented on src/handlers/history.rs
> +    } else {
We have agreed with @enesozturk that the results should be exclusive when we are using the `onramp` without mixing with the Zerions transactions for now.

2023-12-22 03:06 UTC, chris13524 commented on src/providers/coinbase.rs
> +            &address
Ah got it, so looks like there was a bug in the previous commits as well. Makes sense now!

2023-12-22 08:17 UTC, merged