Max/chore/additional instruments
WalletConnect/blockchain-api pull request #391
Opened 2023-11-23 22:09 UTC by geekbrother

# Description

This PR adds additional tracing `instruments` to handlers and providers for the additional span logs in case of errors and for proper debugging.

Resolves #372 

🚧 Stacked on top of the #387 

## How Has This Been Tested?

Logs are exposed with proper tracing instrument spans.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-11-24 16:12 UTC, chris13524 requested changes

2023-11-24 16:12 UTC, chris13524 commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
I don't think we should be logging the address since this isn't in our privacy policy. If anything we can log the hash, but not sure it's worth logging anything at all.

2023-11-24 16:15 UTC, geekbrother commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
The address is currently logging in the [uri section of the span](https://github.com/WalletConnect/blockchain-api/blob/0ebead6182e45c8bc5934050aff97112d032ca15/src/lib.rs#L169). If we are going to remove it, we should remove it from the URI in the span as well.

2023-11-24 16:46 UTC, chris13524 commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
Yeah let's remove 👍

2023-11-27 17:37 UTC, geekbrother commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
I've removed the address from new spans, but if we remove the [URI logging from the middleware](https://github.com/WalletConnect/blockchain-api/blob/0ebead6182e45c8bc5934050aff97112d032ca15/src/lib.rs#L169) we will miss most of the context. Since the address is a part of the URI itself.

2023-11-27 23:25 UTC, chris13524 commented on src/handlers/identity.rs
> +#[tracing::instrument]
Can we `skip_all` here too?

2023-11-27 23:25 UTC, chris13524 commented on src/handlers/identity.rs
> +#[tracing::instrument]
Can we `skip_all` here too so we don't log ENS names?

2023-11-27 23:27 UTC, chris13524 commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
> if we remove the [URI logging from the middleware](https://github.com/WalletConnect/blockchain-api/blob/0ebead6182e45c8bc5934050aff97112d032ca15/src/lib.rs#L169) we will miss most of the context. Since the address is a part of the URI itself.

We don't need to do in this PR but can't we sensor the address when it detects a URL that would contain an address?

2023-11-28 15:08 UTC, geekbrother commented on src/handlers/identity.rs
> +#[tracing::instrument]
done

2023-11-28 15:08 UTC, geekbrother commented on src/handlers/identity.rs
> +#[tracing::instrument]
done

2023-11-28 15:13 UTC, geekbrother commented on src/handlers/identity.rs
> +#[tracing::instrument(skip_all, fields(address = %address))]
Extracted into the #402

2023-11-28 16:34 UTC, chris13524 approved these changes

2023-11-28 16:51 UTC, merged