feat: exposing `implementations` for the transactions history
WalletConnect/blockchain-api pull request #409
Opened 2023-12-08 22:17 UTC by geekbrother

# Description

Exposing the `chain_id` and `address` from the `implementations` for the `fungible_info`.
The updated response will contain the following new exposed fields:
```
{
...
  "transfers":[
    {
      "fungible_info":
        ...
        "implementations": [
              {
                "chain_id": "polygon",
                "address": "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"
              }
            ]
...
}
```

Resolves #408 

## How Has This Been Tested?

Start the server locally by running `cargo run` with a valid Zerion RPC key in `RPC_PROXY_PROVIDER_ZERION_API_KEY` environment variable.
Request the history by the curl command `curl -v 'http://localhost:3000/v1/account/0xf3ea39310011333095CFCcCc7c4Ad74034CABA63/history?projectId=xxx`.
Th expected result is that response should contain the `implementations`.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-12-09 02:44 UTC, tomiir reviewed
This looks good! though I think we would be missing nft chain data 
According to Zerion docs there's an optional `relationships` key that *could* include the chain:
```
pub struct ZerionTransactionsReponseBody {
    pub r#type: String,
    pub id: String,
    pub attributes: ZerionTransactionAttributes,
    pub relationships: ZerionTransactionRelationships
}
```

Check this out: 
<img width="630" alt="image" src="https://github.com/WalletConnect/blockchain-api/assets/12738697/4ea91b57-d73a-4846-8705-709ec26dde89">

The thing is, it's not required.
I think it might be worth asking Zerion team what kind of transactions would have that field populated to check if it serves our purpose

2023-12-09 12:23 UTC, arein commented on src/providers/zerion.rs
> +    pub implementations: Vec<ZerionTransactionImplementation>,
```suggestion
    pub chain_id: String,
```

Tenet of this service is to be provider agnostic. So let's refrain from exposing as much data as possible from Zerion's API and instead expose only the required data such that if we ever want to add another provider it becomes easier.

2023-12-09 12:23 UTC, arein requested changes
Tenet of this service is to be provider agnostic. So let's refrain from exposing as much data as possible from Zerion's API and instead expose only the required data such that if we ever want to add another provider it becomes easier.

2023-12-11 12:34 UTC, chris13524 reviewed
Should there be tests for this? Also shouldn't we normalize the chain ID to a standard number instead of the string?

2024-01-29 11:29 UTC, geekbrother commented
Closing this in favor of #494

2024-01-29 11:29 UTC, closed without merging