feat: add sql schema and migrations
WalletConnect/blockchain-api pull request #411
Opened 2023-12-11 22:36 UTC by geekbrother

# Description

This PR adds SQL database tables schema migration files for the sqlx.

Resolves #405 

## How Has This Been Tested?

TBD

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-12-12 22:51 UTC, chris13524 commented on migrations/20231209213851_init-names.sql
> +CREATE EXTENSION hstore;
Do we have permissions to do this on RDS?

Also, why `hstore` instead of a related table?

2023-12-12 22:52 UTC, chris13524 commented on migrations/20231209213904_init-addresses.sql
> +CREATE TYPE supported_blockchains AS ENUM (
These are actually called "namespaces" not blockchains. Can we change that terminology?

2023-12-12 22:54 UTC, chris13524 commented on migrations/20231209213851_init-names.sql
> +  attributes hstore,
I think the attributes should be part of the `addresses` table, so that way when you change your name it doesn't result in a new set of attributes.

2023-12-12 22:56 UTC, chris13524 commented on migrations/20231209213904_init-addresses.sql
> +  name  VARCHAR(255) REFERENCES  names (name) ON DELETE CASCADE,
What about historical names?

2023-12-12 22:57 UTC, chris13524 commented on migrations/20231209213851_init-names.sql
> +  CONSTRAINT ens_name_standard CHECK (name ~ '^[a-z0-9.-]*$')
How expensive is this?

2023-12-12 22:58 UTC, chris13524 requested changes
I think the structure needs to be changed to support historical names. Also "blockchain" to "namespace"

2023-12-12 23:13 UTC, chris13524 commented on migrations/20231209213851_init-names.sql
> +  name VARCHAR(255) PRIMARY KEY,
Not sure I like using a string as the primary key for linking the table together

2023-12-12 23:13 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +  name  VARCHAR(255) REFERENCES  names (name) ON DELETE CASCADE,
Yes, we have redirects in our specs for the old names. Since it's not on the table now, the idea is to add the table for the redirected old names (that will be added later).

2023-12-12 23:13 UTC, geekbrother commented on migrations/20231209213851_init-names.sql
> +  CONSTRAINT ens_name_standard CHECK (name ~ '^[a-z0-9.-]*$')
Not expensive as this is executed only in insert and update.

2023-12-12 23:17 UTC, geekbrother commented on migrations/20231209213851_init-names.sql
> +CREATE EXTENSION hstore;
Yes, [we have the permission](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html).
With the related table we will have additional queries in each lookup, and no additional queries for the attributes in the case of hstore. by the way, ENS is using it in their gate implementation as well.

2023-12-12 23:18 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +CREATE TYPE supported_blockchains AS ENUM (
I don't mind to change it.

2023-12-12 23:18 UTC, chris13524 commented on migrations/20231209213904_init-addresses.sql
> +  name  VARCHAR(255) REFERENCES  names (name) ON DELETE CASCADE,
I think it would be better to have all the names in 1 table with a UNIQUE key to prevent race conditions.

2023-12-14 10:56 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +CREATE TYPE supported_blockchains AS ENUM (
Thx. Done.

2023-12-14 10:56 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +  name  VARCHAR(255) REFERENCES  names (name) ON DELETE CASCADE,
Makes sense! We can store multiple names with the same addresses (reference to the name from addresses) in this table (part of them can be historical).
`name  VARCHAR(255) REFERENCES  names (name) ON DELETE CASCADE` will delete the address records if the name is deleted (but we will not delete names until the grace period or something we will figure out how our historical names will work). 
We can add an additional field in this table like `is_historical` to mark the name as historical (but this can be done later when we have a clear view on how the registration, domain retention policy will work).
The name is the central entity here because we don't have a `centralized` account_id or something to bind the names to. The name owner is the address owner, but addresses can be a few in different blockchains. What I would add now is that it's clear that one address should be a primary, so we can add `primary(bool)` to the addresses.

2023-12-14 11:01 UTC, geekbrother commented on migrations/20231209213851_init-names.sql
> +  name VARCHAR(255) PRIMARY KEY,
Looks scary, but the name is unique, we don't need to add an additional `id` field here.

2023-12-14 11:03 UTC, geekbrother commented
> I think the structure needs to be changed to support historical names. Also "blockchain" to "namespace"

Gave my thoughts [in the comment](https://github.com/WalletConnect/blockchain-api/pull/411#discussion_r1426564431).

2023-12-14 14:51 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +  PRIMARY KEY (name, namespace, chain_id, address)
The `chain_id` is changed to can't be NULL, but can be an empty string instead to represent mainnet on some of the chains, because it should be part of the composite unique key for the address, but the unique primary key field can't be NULL and NULL can't be constraint. So this is handled by the empty string [further in helpers](https://github.com/WalletConnect/blockchain-api/pull/413/files#diff-98120810190356016b1026cd118005a84df034f5114b17bef040bf69f9aad917R199). In this case we can use it as generic solution for all chains.

2023-12-15 22:58 UTC, chris13524 approved these changes
Just one name change I think is necessary, but otherwise LGTM.

I'm a little scared about the hstore and the 4-item primary key, but I haven't used those things before and am willing to try them out. I'm sure we can always change and migrate the data later so all good.

2023-12-15 22:58 UTC, chris13524 commented on migrations/20231209213904_init-addresses.sql
> +  namespace namespaceses,
"namespaces" is the plural of "namespace"

```suggestion
  namespace namespaces,
```

2023-12-18 11:30 UTC, geekbrother commented on migrations/20231209213904_init-addresses.sql
> +  namespace namespaceses,
Fixed! Thanks for catching this.

2023-12-18 21:53 UTC, merged