feat: implement database helpers
WalletConnect/blockchain-api pull request #413
Opened 2023-12-11 22:58 UTC by geekbrother

# Description

this PR adds the database helpers implementation.

Resolves #450

## How Has This Been Tested?

TBD

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-12-12 23:17 UTC, chris13524 requested changes

2023-12-12 23:17 UTC, chris13524 commented on src/database/helpers.rs
> +          (SELECT name FROM addresses WHERE address = $1)
Can we use a JOIN instead of a subquery?

2023-12-12 23:17 UTC, chris13524 commented on src/database/helpers.rs
> +          (SELECT name FROM addresses WHERE address = $1 AND blockchain = $2)
Can we use a JOIN instead of a subquery?

2023-12-12 23:17 UTC, chris13524 commented on src/database/helpers.rs
> +pub async fn insert_name(
Missing idempotency/conflict handling

2023-12-12 23:17 UTC, chris13524 commented on src/database/helpers.rs
> +    if let Some(ref chain_id_value) = chain_id {
Can't you provide `None` to `bind()` instead of needing a separate query for this case?

2023-12-12 23:17 UTC, chris13524 commented on src/database/helpers.rs
> +    let addresses = get_addresses_by_name(name, postgres).await?;
Ideally this would be 1 database query with the list of addresses returned with e.g. `array_agg()` function. This avoids multiple round trips.

Alternatively would be nice to do these two queries in parallel to reduce execution time.

2023-12-14 14:53 UTC, geekbrother commented on src/database/helpers.rs
> +    let addresses = get_addresses_by_name(name, postgres).await?;
That makes sense. I'll defer it for now, but fire an issue to track right after we merge the PRs stack. Thx.

2023-12-14 14:55 UTC, geekbrother commented on src/database/helpers.rs
> +          (SELECT name FROM addresses WHERE address = $1 AND blockchain = $2)
Done. Thx.

2023-12-14 15:06 UTC, geekbrother commented on src/database/helpers.rs
> +pub async fn insert_name(
We will check if the name is already registered in the registration handler by the name lookup, then check the signature, and then call this function to insert. There will be a sqlx error in case someone got the name (constraint error, that will be handled on the handler side) while these 3 steps in handler executed.
Ideally, we can do the registration flow in one transaction so we will not have such race conditions in a registration process. 
But we can think about it later (I'll create a followup issue for that).
At the moment we have to check the name availability and signature before to call this inserting.

2023-12-15 23:16 UTC, chris13524 approved these changes
LGTM

2023-12-19 20:50 UTC, merged