feat: name registration handler [draft]
WalletConnect/blockchain-api pull request #418
Opened 2023-12-14 19:30 UTC by geekbrother

# Description

This PR implements the name registration handler according to the [SPEC](https://github.com/WalletConnect/walletconnect-specs/pull/184)

Resolves #405

## How Has This Been Tested?

Integration tests TBD.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-12-15 23:37 UTC, chris13524 requested changes

2023-12-15 23:37 UTC, chris13524 commented on src/handlers/profile/mod.rs
> +    // Hash the prefixed message with keccak256
https://www.youtube.com/watch?v=k5DJxz6_xMA

2023-12-15 23:37 UTC, chris13524 commented on src/handlers/profile/mod.rs
> +    let properly_escaped_string = message.replace('"', "\\\"");
Something is wrong here, I don't think we need to or should be doing a second layer of escaping, just remove the escapes from https://github.com/WalletConnect/blockchain-api/pull/419/files#diff-29ee1e76a6651d33c3e1a5117e948675ccda1e60165c885696a9accdc1bf0bb9R169

The thing you're signing should just be JSON with no escapes:
```
\x19Ethereum Signed Message:
{"some":"json object"}
```

2023-12-17 17:38 UTC, geekbrother commented on src/handlers/profile/mod.rs
> +    let properly_escaped_string = message.replace('"', "\\\"");
Ok, I agree that this double-escaping approach smells...
I've removed it in favor of just `{"some":"json object"}`, let's see how it goes under the dogfooding (is it confusing for the devs and users, or not).

2023-12-17 22:35 UTC, chris13524 approved these changes

2023-12-17 22:35 UTC, chris13524 commented on src/handlers/profile/mod.rs
> +        let message = "{\\\"test\\\":\\\"some my text\\\"}";
Raw strings can help here with the escape confusion:

```suggestion
        let message = r#"{\"test\":\"some my text\"}"#;
```

Also, shouldn't this be updated to not have the escapes?

2023-12-20 23:48 UTC, geekbrother commented on src/handlers/profile/mod.rs
> +        let message = "{\\\"test\\\":\\\"some my text\\\"}";
I don't mind changing it to the raw string to remove the ugly `\\\`.

> Also, shouldn't this be updated to not have the escapes? Guess it doesn't really matter because this is a generic signature validation test.

Yes, it doesn't matter what the signed string looks like, but as we are using the escaped JSON in our checks let's stick to it on test as well.

Thanks for the comments!

2023-12-20 23:53 UTC, merged