feat(ci): profile names integration tests
WalletConnect/blockchain-api pull request #419
Opened 2023-12-15 01:08 UTC by geekbrother

# Description

This PR adds implementation for the integration tests for the account names.

Resolves #405 

## How Has This Been Tested?

* Start the server with the: `cargo run --features "test-localhost"`
* Run the integration test within the local server: `PROJECT_ID=xxxxx RPC_URL=http://localhost:3000 yarn integration`

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-12-15 23:39 UTC, chris13524 requested changes

2023-12-15 23:39 UTC, chris13524 commented on integration/integration.test.ts
> +    const new_domain_valid_message = '{\"name\":\"newname.connect.id\",\"address\":\"0xaff392551773ccb2574fae23195cc3afdbe98d18\",\"timestamp\":242342342432}';
Same as https://github.com/WalletConnect/blockchain-api/pull/418#discussion_r1428585753 just remove the escapes here

2023-12-15 23:39 UTC, chris13524 commented on integration/integration.test.ts
> +    const new_domain_valid_signature = '0x2b9b288babb26be665a19ddaf71b8ecb300f8101e468c86401d9f5b57284352f084906c7017708e243e13c8484f73ee71da9e6a8a090166e1bc128090325d7571b'
Please generate this signature dynamically (via randomly generated account) so that it's easier to adjust the message format or generate new test cases without needing to contact the person with the private key.

2023-12-18 21:26 UTC, geekbrother commented on integration/integration.test.ts
> +    const new_domain_valid_signature = '0x2b9b288babb26be665a19ddaf71b8ecb300f8101e468c86401d9f5b57284352f084906c7017708e243e13c8484f73ee71da9e6a8a090166e1bc128090325d7571b'
This is a good point, thanks! 
It's changed now to use dynamic values.

2023-12-18 23:37 UTC, chris13524 approved these changes

2023-12-22 13:13 UTC, merged