feat(history): exposing dapp and chain info
WalletConnect/blockchain-api pull request #494
Opened 2024-01-29 11:22 UTC by geekbrother

# Description

This PR exposes the `chain` from the [Zerion history](https://developers.zerion.io/reference/listwallettransactions) `relationships` object and the dapp info from the `attributes.application_metadata`.

Following new objects were added into the history response:

* metadata.application
  * name (Optional, String) - DApp name
  * iconUrl (Optional, String) - DApp icon url
* metadata.chain (Optional, String) - String representation of the chain from the `relationships` Zerion response.

The example response:

```
...
{
      "id": "904c7ac7e1dc5ddd9aed4ceba06ee290",
      "metadata": {
        "operationType": "receive",
        "hash": "0x0f12fde4d498ad01baa181f433ad46ff6ce760af5bfe388418c243f2e2fb168b",
        "minedAt": "2023-12-04T11:02:25Z",
        "sentFrom": "0xd09a341d601505b0c8a0377acc962802e5f3fb65",
        "sentTo": "0x2c27e884cbe02252587ef62c5647ecb9a8936f3e",
        "status": "confirmed",
        "nonce": 76792,
        "application": { // NEW DAPP OBJECT
          "name": "USDC",
          "iconUrl": "https://token-icons.s3.amazonaws.com/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.png"
        },
        "chain": "xdai" // NEW CHAIN STRING
      },
      "transfers": [
      ...
      ]
    },
...
```

## How Has This Been Tested?

1. Manual
* Start the server locally by: `cargo run`
* Run the curl query to get the transactions list: `curl -v 'http://localhost:3000/v1/account/0x63755B7B300228254FB7d16321eCD3B87f98ca2a/history?projectId=xxx' | jq .`

2. Integration tests for the fulfilled history are updated to check new objects' presence.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-01-29 11:24 UTC, geekbrother commented on src/providers/zerion.rs
> +    pub transfers: Vec<ZerionTransactionTransfer>,
Removing dependency from the `HistoryTransactionTransfer` structure here, because our response differs from the Zerion transaction response in this part since now.

2024-01-29 11:26 UTC, alanaladd21 commented on src/providers/coinbase.rs
>                      status: f.status,
remove dependencies

2024-01-29 11:27 UTC, geekbrother commented on src/providers/coinbase.rs
>                      status: f.status,
What exactly dependencies should be removed @alanaladd21 ?

2024-01-29 11:30 UTC, glitch-txs approved these changes

2024-01-29 15:31 UTC, arein requested changes
can you make the chain id `caip25`?

2024-01-29 17:45 UTC, glitch-txs commented
let's expose it as it is now imo, then it would be great to abstract this into CAIP chains format

2024-01-29 18:04 UTC, chris13524 commented
Am also in-favor of using CAIP-25 here. How will frontend consume this? I assume they'd have to do the mapping on their end anyway

2024-01-29 18:24 UTC, glitch-txs commented
> How will frontend consume this? 
on the wagmi side, Viem has a chain registry with all the chain data, so we'd map against that but we'd need to check if the naming matches which is not ideal.
This is for the Activity tab mainly

cc @tomiir

2024-01-29 18:43 UTC, tomiir commented
Honestly not sure we'd need to map anything given the chainId and the icon are present in the response and with that we could filter txs by chain and render appropiate icons/images. 

Am I missing some use-case @glitch-txs ?

2024-01-29 18:44 UTC, glitch-txs commented
Yep, filtering I meant

2024-01-29 20:57 UTC, chris13524 commented
> Honestly not sure we'd need to map anything given the chainId and the icon are present in the response and with that we could filter txs by chain and render appropiate icons/images.

I presume filtering requires obtaining the chain name. What registry will you use to lookup the chain name and icon?

2024-01-29 21:02 UTC, geekbrother commented
> > Honestly not sure we'd need to map anything given the chainId and the icon are present in the response and with that we could filter txs by chain and render appropiate icons/images.
> 
> I presume filtering requires obtaining the chain name. What registry will you use to lookup the chain name and icon?

Looks like [Viem doesn't have an icon](https://github.com/wevm/viem/blob/main/src/chains/definitions/arbitrum.ts) cc @glitch-txs

2024-01-29 21:03 UTC, chris13524 commented
I think @arein and I are actually referring to [CAIP-2](https://chainagnostic.org/CAIPs/caip-2) not CAIP-25.

> on the wagmi side, Viem has a [chain registry with all the chain data](https://github.com/wevm/viem/tree/main/src/chains/definitions), so we'd map against that but we'd need to check if the naming matches which is not ideal.

@glitch-txs Viem has a [method](https://rc.viem.sh/docs/utilities/extractChain.html) to find a chain by it's CAIP-2 chain ID. So blockchain API should return a CAIP-2 chain ID e.g. `eip155:1` and then the client would ensure that it has the `eip155` namespace and then pass the `reference` as the `id` parameter to `extractChain()`

2024-01-29 21:09 UTC, glitch-txs commented
returning the chain ID would be ideal as we make sure there are no conflicts with naming which sometimes can be ambiguos, e.g. in ethers devs config the chains themselves so the could you any name but it's better to rely on the chain ID which we know it's going to be more accurate.
Images are taken from the cloud with specifics ID that are keyed with chain IDs.

So:

- Ideally the best would be to get the chain ID of each transaction
- If we receive names we can use Viem registry to look for the matching name and return the ID from it, but this wouldn't work in ethers.

I really don't understand why this API returns a name in a chain_id flag xD

2024-01-29 21:11 UTC, geekbrother commented
> I really don't understand why this API returns a name in a chain_id flag xD should we report this as well? 🤔

I've asked the Zerion team in a Discord, what was the reason for this )

2024-01-30 12:26 UTC, geekbrother commented
Updates:
* Now we are trying to convert the chain id to the CAIP-2 format by the [function that uses ethers::types::Chain](https://github.com/WalletConnect/blockchain-api/pull/494/files#diff-43dc5270da6ae7bd3fbe8ee20c85643dcc3d3fb0feba36ad76570b327ef51667R38) and return the converted CAIP-2. Not all chains are there but most used are in.
* If it fails to find the chain from the human-readable list we will return the chain id as is and log an `info!` (I'll monitor these logs to find what aliases are probably missing to add it).
* Tested on a few addresses with a different history.

cc @chris13524, @glitch-txs, @tomiir, @arein

2024-01-30 12:41 UTC, glitch-txs approved these changes

2024-01-30 16:29 UTC, chris13524 requested changes

2024-01-30 16:29 UTC, chris13524 commented on src/providers/zerion.rs
> +                                Some(f.relationships.chain.data.id)
I don't think we should fallback to an invalid value. Instead, the entry should be excluded from the results list.

2024-01-30 16:33 UTC, geekbrother commented on src/providers/zerion.rs
> +                                Some(f.relationships.chain.data.id)
I don't mind changing it to excluded in this case, but passing it through, we could catch the unsupported chain id at both the backend and frontend side, assuming that on the frontend side, there is a check for the CAIP-2 format, and if it's not, just behave like it's excluded.

2024-01-30 16:40 UTC, chris13524 commented on src/providers/zerion.rs
> +                                Some(f.relationships.chain.data.id)
Why error in the client at all? We don't support the chain. We don't need to cause more errors

2024-01-30 16:50 UTC, geekbrother commented on src/providers/zerion.rs
> +                                Some(f.relationships.chain.data.id)
I'm not speaking about the error on the frontend side:

> assuming that on the frontend side, there is a check for the CAIP-2 format, and if it's not, just behave like it's excluded.

If there is a strong opinion not passing it through, I'll just exclude it in this case to unblock this feature asap.

2024-01-30 16:59 UTC, geekbrother commented on src/providers/zerion.rs
> +                                Some(f.relationships.chain.data.id)
[Just changed it](https://github.com/WalletConnect/blockchain-api/pull/494/commits/155db8ba40d19fa219a171512c29153f5847b8e7) to not pass through in case if it's not caip-2.

2024-01-31 12:45 UTC, geekbrother commented
> can you make the chain id `caip25`?

Now it's CAIP-2 compatible. cc @arein.

2024-01-31 13:48 UTC, chris13524 approved these changes

2024-01-31 13:48 UTC, chris13524 commented on src/providers/zerion.rs
> +                                None
My thinking was actually that if the chain wasn't supported, then the transaction wouldn't appear in the list, not that the chain would be `null`. `null` would presumably still cause an error whereas skipping over transactions on an unsupported chain would be different. However, it's possible clients could recover by displaying a fallback image if that's all they need to do.

2024-01-31 13:53 UTC, geekbrother commented on src/providers/zerion.rs
> +                                None
> However, it's possible clients could recover by displaying a fallback image if that's all they need to do.

I think that's the plan, right? cc @tomiir

2024-01-31 13:59 UTC, arein commented on integration/integration.test.ts
> +      expect(first.metadata.chain).toBeDefined()
Plus one this leaves a lot of room for regressions

2024-01-31 14:31 UTC, geekbrother commented
Just updated the integration test to check the `chain` is either CAIP-2 format or null.

2024-01-31 14:40 UTC, merged