feat(ens): updating name address handler
WalletConnect/blockchain-api pull request #510
Opened 2024-02-08 18:21 UTC by geekbrother

# Description

This PR adds an endpoint handler to update the name address according to the SPEC.

The following changes are made:

* `POST /v1/profile/account/:name/address` endpoint is added to handle the name address updating,
  * Updated name address map returns as a result.
* [Integration test](https://github.com/WalletConnect/blockchain-api/pull/509/files#diff-28b661942cfc4edae43683709afac7c88cdd3d5bdcc47e602ee9ea4c876dbaf1R129-R157) for the new endpoint to check the name addresses after updating.

## How Has This Been Tested?

The integration test was added to this PR.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-02-08 20:09 UTC, chris13524 requested changes

2024-02-08 20:09 UTC, chris13524 commented on src/handlers/profile/address.rs
> +            Err(_) => {
This can fail for reasons other than the row not existing, e.g. database error

2024-02-09 11:35 UTC, geekbrother commented on src/handlers/profile/address.rs
> +            Err(_) => {
[Fixed](https://github.com/WalletConnect/blockchain-api/pull/510/commits/3387ca929fdca3f3b7fffcda86587fca86dd699e). Thanks for catching this!

2024-02-09 19:09 UTC, chris13524 approved these changes
LGTM

2024-02-09 21:49 UTC, merged