fix(monitoring): increasing CPU alarm threshold
WalletConnect/blockchain-api pull request #539
Opened 2024-02-27 22:09 UTC by geekbrother

# Description

This PR increases the CPU utilization alarm threshold to 25 minutes same as we have in the Relay to allow autoscaling provisioning and alarm if it's not scaled along with the high CPU usage.

## How Has This Been Tested?

Not tested.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-02-27 22:10 UTC, nopestack approved these changes

2024-02-27 22:11 UTC, chris13524 requested changes

2024-02-27 22:11 UTC, chris13524 commented on terraform/monitoring/panels/ecs/cpu.libsonnet
> +          queryTimeStart  = '25m',
Changing the query start take makes it still a no-op

2024-02-27 22:20 UTC, geekbrother commented on terraform/monitoring/panels/ecs/cpu.libsonnet
> +          queryTimeStart  = '25m',
[We have the same parameters in Relay](https://github.com/WalletConnect/rs-relay/blob/67be2244b8950117eafe429467ef6df2b980b009/terraform/monitoring/panels/app/app_cpu_memory.libsonnet#L20-L33). I'm assuming that the query time start and period should be the same to trigger on the same timeframe.

2024-02-28 22:29 UTC, chris13524 approved these changes

2024-02-28 22:31 UTC, merged