fix: supported chains endpoint
WalletConnect/blockchain-api pull request #571
Opened 2024-03-08 00:23 UTC by chris13524

# Description

Adds a basic endpoint to return a list of supported CAIP-2 chain IDs.

Resolves #566 

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-03-08 09:08 UTC, nopestack approved these changes
Lgtm

2024-03-08 09:08 UTC, nopestack commented on src/providers/mod.rs
> +            supported_chains: HashSet::new(),
Consider simply calling `..Default::default` to avoid setting all of these empty HashSets/Maps

2024-03-08 09:37 UTC, geekbrother requested changes
Requesting changes, because I see an issue here:
* Why only ws supported chains were added? In this case, the return should reflect this somehow, e.g. move this list into the `ws` entity of the response.

The test:
`curl -v 'http://localhost:3000/v1/supported-chains?projectId=xxx' | jq .`, the response:
```
[
  "eip155:420",
  "eip155:1",
  "eip155:5",
  "eip155:42161",
  "eip155:10",
  "eip155:11155111",
  "eip155:421613",
  "eip155:7777777"
]
```
There are only ws supported chains.

I think this endpoint should reflect the `SUPPORTED_CHAINS.md`.

2024-03-08 15:55 UTC, chris13524 commented
@geekbrother oops! Yeah meant to do HTTP RPC not WS supported chains. Good catch.

I suppose I'll put the list of HTTP RPC supported chains in an `http` entity of the response to allow room to support `ws` in the future? WS is deprecated and will probably be removed. Maybe I'll just put both `http` and `ws` in there, might as well and easy enough and models current structure of everything.

2024-03-08 15:57 UTC, chris13524 commented on src/providers/mod.rs
> +            supported_chains: HashSet::new(),
`Self` doesn't implement `Default`

2024-03-11 15:14 UTC, geekbrother approved these changes
Nice!

2024-03-11 16:01 UTC, merged