feat(sessions): implementing permission revoking
WalletConnect/blockchain-api pull request #699
Opened 2024-07-08 17:26 UTC by geekbrother

# Description

This PR implements the permission context revoking endpoint `/v1/sessions/{address}/revoke` according to the [API SPEC draft](https://github.com/WalletConnect/walletconnect-specs/pull/242).

For the request authentication, the signature (signed message) is used. 
As a signing message, the permission controller unique identifier is used (PCI) and signed by the signing key (created during the session creation request). 
Then the signature is verified at the server by the verification key which is stored during the [session creation](https://github.com/WalletConnect/walletconnect-specs/pull/242/files#diff-585df27a5f0c0b1216c7296d8bbe3c30877bc469bcbdad4c905c6803c1e441dcR53) in the permission session object.

## How Has This Been Tested?

* A new integration test was implemented.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-07-10 16:38 UTC, chris13524 commented on src/handlers/sessions/revoke.rs
> +    state.metrics.add_irn_latency(irn_call_start, "hget".into());
Would be good to make this `"hget"` thing an enum

2024-07-10 16:42 UTC, chris13524 requested changes
I think this needs to be idempotent

2024-07-10 16:42 UTC, chris13524 commented on src/handlers/sessions/revoke.rs
> +        .ok_or_else(|| RpcError::PermissionNotFound(request_payload.pci.clone()))?;
Shouldn't this result in a 2xx status code rather than a 4xx one? Idempotency?

2024-07-12 12:39 UTC, geekbrother commented on src/handlers/sessions/revoke.rs
> +        .ok_or_else(|| RpcError::PermissionNotFound(request_payload.pci.clone()))?;
The user trying to revoke permission which does not exist, so the passed PCI is not correct, that's why we are returning `Bad Request` here, pointing out that the passed parameter is wrong.

2024-07-12 13:10 UTC, geekbrother commented on src/handlers/sessions/revoke.rs
> +    state.metrics.add_irn_latency(irn_call_start, "hget".into());
Good catch, we should get rid of magic string. Fixed in 4cf2436ddb2982e35acc239be410694daace0ea6 by implementing `OperationType` enum.

2024-07-12 16:11 UTC, chris13524 commented on src/handlers/sessions/revoke.rs
> +        .ok_or_else(|| RpcError::PermissionNotFound(request_payload.pci.clone()))?;
What if it was already revoked but the client didn't get back the response (e.g. error in network), then it would try to revoke a second time and then get an error it doesn't expect.

Why not just return OK if it's already revoked?

2024-07-12 16:12 UTC, chris13524 commented on src/handlers/sessions/context.rs
> +        .add_irn_latency(irn_call_start, OperationType::Hget.into());
Good to change to enum but I would go a step further and convert the enum into a string _inside_ `add_irn_latency()`

2024-07-12 16:29 UTC, chris13524 approved these changes
I think the revoke endpoint should be idempotent

2024-07-12 16:38 UTC, geekbrother commented on src/handlers/sessions/revoke.rs
> +        .ok_or_else(|| RpcError::PermissionNotFound(request_payload.pci.clone()))?;
Let's return OK, but shoot a `warning!` in this case to track possible issues with that.

2024-07-12 18:40 UTC, geekbrother commented
> I think the revoke endpoint should be idempotent

I missed that we need to check the request signature later, we need to get the verifying key for that. If the PCI not exists we can't verify/authorize the request.

2024-07-12 19:01 UTC, chris13524 commented
> I missed that we need to check the request signature later, we need to get the verifying key for that. If the PCI not exists we can't verify/authorize the request.

You only need to verify it if you are going to perform an action. If the action is already performed then you are good.

2024-07-12 20:06 UTC, geekbrother commented
> > I missed that we need to check the request signature later, we need to get the verifying key for that. If the PCI not exists we can't verify/authorize the request.
> 
> You only need to verify it if you are going to perform an action. If the action is already performed then you are good.

Changed it. We are returning [OK and warn on it](https://github.com/WalletConnect/blockchain-api/pull/699/commits/8fd31b1f6d383ce14128e44d79b4c7f1812cd200) now.

2024-07-12 20:17 UTC, geekbrother commented on src/handlers/sessions/context.rs
> +        .add_irn_latency(irn_call_start, OperationType::Hget.into());
Done https://github.com/WalletConnect/blockchain-api/pull/699/commits/3ddc187089112ae5f55339a813a3de4bbe815ff4. Thanks!

2024-07-12 20:47 UTC, merged