fix: add proxy timeout
WalletConnect/blockchain-api pull request #734
Opened 2024-08-16 17:53 UTC by chris13524

# Description

This adds a 10s timeout to call providers. Metrics show that sometimes endpoints can sometimes take a long time to respond and this could lead to 504 errors.

<img width="1150" alt="Screenshot 2024-08-16 at 13 53 22" src="https://github.com/user-attachments/assets/1975be1e-40d6-4247-b126-dcb9fb13fe9a">

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-08-17 11:58 UTC, geekbrother commented
I believe we want to return `HTTP 503` in case of the timeout. We are returning `HTTP 500` currently.

2024-08-17 11:59 UTC, geekbrother requested changes
I believe we want to return `HTTP 503` in case of the timeout. We are returning `HTTP 500` currently.

2024-08-19 18:53 UTC, chris13524 commented
> Thanks for adding this! I believe we want to return HTTP 503 in case of the timeout. We are returning HTTP 500 currently.

@geekbrother good catch 🙏 I've modified the code to retry for all server-related errors

2024-08-19 20:27 UTC, geekbrother commented on src/handlers/proxy.rs
> +            Ok(response) if !response.status().is_server_error() => {
That's a great catch to move to the next provider not only when 503 👍

2024-08-19 20:28 UTC, geekbrother approved these changes
Thanks for adding this 👍

2024-08-20 15:59 UTC, chris13524 commented on src/handlers/proxy.rs
> +            _ => {
Good catch, added in [b39387e](https://github.com/WalletConnect/blockchain-api/pull/734/commits/b39387e259c19d8f01b4d915bee28bc1fe541468)

2024-08-20 15:59 UTC, merged